------ LOAD ------
-- This script loads the data from an external file and stores it into a table called "DATASET."
-- run using (-tvf) 

---- INITIALIZATION ----

CONNECT TO SAMPLE; -- CONNECT TO DATABASE

CREATE TABLE DATASET("PID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1, NO CACHE ) , "CLASS" VARCHAR (10), "TYPE" VARCHAR (10),"SEX" VARCHAR (10),"SURVIVED" VARCHAR (10)); -- CREATE TABLE WITH NAME DATASET AND FIELDS SIMILAR TO TITANIC DATASET

---- LOAD FROM DATA FILE OF DATASET ----

LOAD FROM 'C:/Users/Ronak Sumbaly/Downloads/Dataset.data' OF del INSERT INTO DATASET(Class, Type, Sex, Survived); -- LOAD DATASET FROM LOCAL DISK

CONNECT RESET ; -- RESET CONNECTION
TERMINATE; -- TERMINATE DB2 PROCESS