------ TEST ------
-- This script is used to test the model of the training data with the test dataset

---- INITIALIZATION ----

CONNECT TO SAMPLE;

-- drop tables 
DROP TABLE TEST_RESULTS;
DROP TABLE COMBINED_RESULTS;

-- create tables 
CREATE TABLE TEST_RESULTS("COLUMN" INTEGER, "ACTUAL" VARCHAR(10), "PREDICTED" VARCHAR(10));
CREATE TABLE COMBINED_RESULTS("ACCURACY" DECIMAL(11,10));

INSERT INTO TEST_RESULTS(COLUMN, ACTUAL, PREDICTED)
	WITH
		PROBABILITY(ROW, PREDICTED, PROB) AS
		(SELECT TEST_DATASET.PID, NBC.DECISION, NBC.PROBABILITY
			FROM TEST_DATASET, NBC
			WHERE TEST_DATASET.COLUMNNO = NBC.COL 
			AND TEST_DATASET.ATT = NBC.ATT),
		PROBABILITYSUM(ROW, PREDICTED, PROB) AS
		(SELECT ROW, PREDICTED, SUM(LOG(PROB)) FROM PROBABILITY GROUP BY ROW, PREDICTED),
		WEIGHTPROB(ROW, PREDICTED, PROB) AS
		(SELECT PROBABILITYSUM.ROW, PROBABILITYSUM.PREDICTED, PROBABILITYSUM.PROB + LOG(NBC.PROBABILITY)
		FROM PROBABILITYSUM, NBC
		WHERE PROBABILITYSUM.PREDICTED = NBC.DECISION),
		MAXPROB(ROW, PROBABILITY) AS
		(SELECT ROW, MAX(PROB) FROM WEIGHTPROB GROUP BY ROW)
	(SELECT TD.PID, TD.DECISION, WP.PREDICTED
	FROM TEST_DATASET as TD, MAXPROB as MP, WEIGHTPROB AS WP
	WHERE TD.PID = MP.ROW
	AND TD.PID = WP.ROW
	AND MP.PROBABILITY = WP.PROB
	AND TD.COLUMNNO = 1);
	

INSERT INTO COMBINED_RESULTS(ACCURACY)
	WITH
		SUCCESS(NUM) AS
			(SELECT COUNT(PREDICTED) FROM TEST_RESULTS WHERE PREDICTED = ACTUAL),
		TOTAL(NUM) AS
			(SELECT COUNT(PREDICTED) FROM TEST_RESULTS)
		(SELECT CAST(SUCCESS.num AS DECIMAL(10,0))/CAST(TOTAL.num AS DECIMAL(10,0))
		FROM SUCCESS, TOTAL);

	