------ NBC ------
-- This script creates the NBC and NBC_class tables. NBC is a Naive
-- Bayesian Classifier that gives us P(a|c) for some attribute a and
-- classifier c. NBC_class gives us P(c).

-- This script should be run after partition.sql

---- INITIALIZATION ----

CONNECT TO SAMPLE;

-- drop tables 
DROP TABLE NBC;
DROP TABLE NBC_CLASS;

-- create the tables
CREATE TABLE NBC("COL" INTEGER, "ATT" VARCHAR(10), "DECISION" VARCHAR(10), "PROBABILITY" DECIMAL(11,10));
CREATE TABLE NBC_CLASS("DECISION" VARCHAR(10), "PROBABILITY" DECIMAL(11,10));

INSERT INTO NBC(COL, ATT, DECISION, PROBABILITY)
	WITH GROUPED_DATA(COLUMNNO, DECISION, ATT, SUM_WEIGHT) AS 
	(SELECT COLUMNNO, DECISION, ATT, SUM(WEIGHT)
	 	FROM TRAIN_DATASET
		 GROUP BY GROUPING SETS((COLUMNNO,DECISION), (COLUMNNO, DECISION, ATT)))
	(SELECT GD1.COLUMNNO, GD1.ATT, GD1.DECISION,
			CAST(GD1.SUM_WEIGHT AS DECIMAL(6,0)) / CAST(GD2.SUM_WEIGHT AS DECIMAL(6,0))
			FROM GROUPED_DATA AS GD1 , GROUPED_DATA AS GD2
			WHERE GD1.COLUMNNO = GD2.COLUMNNO
			AND GD1.DECISION = GD2.DECISION
			AND GD1.ATT IS NOT NULL
			AND GD2.ATT IS NULL);
			
INSERT INTO NBC_CLASS(DECISION, PROBABILITY)
	WITH TotalCount(VALUE) AS (SELECT SUM(WEIGHT) FROM TRAIN_DATASET WHERE COLUMNNO = 1),
		ClassCount(DECISION, VALUE) AS (SELECT DECISION, SUM(WEIGHT) FROM TRAIN_DATASET WHERE COLUMNNO = 1 GROUP BY DECISION)
	(SELECT classObj.DECISION,
			CAST(classObj.VALUE AS DECIMAL(10,0)) / CAST(totalObj.VALUE AS DECIMAL(10,0)) 
			FROM TotalCount as totalObj, ClassCount as classObj);
				
CONNECT RESET;
TERMINATE;			
	
	